# Site settings
title: GitHub Essentials
email: me@githubessentials.com
description: > # this means to ignore newlines until "baseurl:"
  A book about GitHub basics.
baseurl: "/github-essentials/" # the subpath of your site, e.g. /blog/
url: "http://axilleas.me" # the base hostname & protocol for your site
twitter_username: _axil
github_username:  axilleas

# Build settings
markdown: kramdown
